#!/usr/bin/env bash
# Installs and properly configures an NGINX server

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.html

sudo sed -i "/server_name _;/a rewrite ^/redirect_me https://youtu.be/WPkMUU9tUqk permanent;" /etc/nginx/sites-available/default

sudo service nginx start
