#!/usr/bin/env bash
# installs nginx
apt-get -y update
apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://youtu.be/WPkMUU9tUqk permanent;" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
service nginx start
