#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
# Displays "I am invinciblle!!!" when receiving a SIGTERM signal
file=/var/run/holbertonscript.pid
trap 'echo Y U no love me?!' SIGINT
trap 'rm $file; exit' SIGQUIT
trap 'echo I hate the kill command; rm $file; exit' SIGTERM
echo $$ > "$file"
while true; do
	echo To infinity and beyond
	sleep 2
done
