#!/usr/bin/env bash
# Displays "Holberton School" 10 times but displays
# "Holberton School" and then "Hi" on a new line
i=0
while [ $((i++)) -lt 10 ]; do
	echo "Holberton School"
if [ $i == 9 ]; then
	echo "Hi"
fi
done
